name = "fgif"
author = "Jacob Williams"
copyright  = "Copyright (c) 2014-2022, Jacob Williams"
license = "BSD-3"
description = "Create Animated GIFs with Fortran"
homepage = "https://github.com/jacobwilliams/fgif"
keywords = ["gif"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[library]
source-dir = "src"

[install]
library = true